// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxQgp8pJt3SCSxVtmlUWIP73IeLsNjqNo',
    appId: '1:647449623193:web:1440d6dc1fcfd3f1fa5608',
    messagingSenderId: '647449623193',
    projectId: 'shopping-list-55669',
    authDomain: 'shopping-list-55669.firebaseapp.com',
    storageBucket: 'shopping-list-55669.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwR44Ie0feCexR66udyClSYzkYaX9tMsg',
    appId: '1:647449623193:android:31890a588f828f0cfa5608',
    messagingSenderId: '647449623193',
    projectId: 'shopping-list-55669',
    storageBucket: 'shopping-list-55669.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_lH7tV-Yf6JZPPgtFeDhacMfvLLcPLxI',
    appId: '1:647449623193:ios:f4b3fe4f162f1196fa5608',
    messagingSenderId: '647449623193',
    projectId: 'shopping-list-55669',
    storageBucket: 'shopping-list-55669.firebasestorage.app',
    iosBundleId: 'com.example.shoppingList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_lH7tV-Yf6JZPPgtFeDhacMfvLLcPLxI',
    appId: '1:647449623193:ios:f4b3fe4f162f1196fa5608',
    messagingSenderId: '647449623193',
    projectId: 'shopping-list-55669',
    storageBucket: 'shopping-list-55669.firebasestorage.app',
    iosBundleId: 'com.example.shoppingList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxQgp8pJt3SCSxVtmlUWIP73IeLsNjqNo',
    appId: '1:647449623193:web:c2174991fc4b9ed8fa5608',
    messagingSenderId: '647449623193',
    projectId: 'shopping-list-55669',
    authDomain: 'shopping-list-55669.firebaseapp.com',
    storageBucket: 'shopping-list-55669.firebasestorage.app',
  );
}
